# Generated by Django 2.1.2 on 2018-10-14 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0006_auto_20181014_2247'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='business',
            options={'ordering': ('active', 'name'), 'verbose_name': 'Business', 'verbose_name_plural': 'Businesses'},
        ),
        migrations.AlterModelOptions(
            name='module',
            options={'ordering': ('active', '-end_time', 'name'), 'verbose_name': 'Module', 'verbose_name_plural': 'Modules'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ('active', '-end_time', 'name'), 'verbose_name': 'Product', 'verbose_name_plural': 'Products'},
        ),
    ]
