# Generated by Django 2.1.2 on 2018-10-14 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0008_auto_20181014_2254'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25, verbose_name='Name')),
                ('description', models.TextField(verbose_name='Description')),
                ('active', models.BooleanField(default=True, verbose_name='Status')),
            ],
            options={
                'verbose_name': 'Tag',
                'verbose_name_plural': 'Tags',
                'ordering': ('-active', 'name'),
            },
        ),
        migrations.AddField(
            model_name='zentaocase',
            name='tags',
            field=models.ManyToManyField(blank=True, null=True, to='cases.Tag', verbose_name='Tags'),
        ),
    ]
