# Generated by Django 2.1.2 on 2018-11-14 15:43

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0011_auto_20181114_2340'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zentaocase',
            name='maintainers',
            field=models.ManyToManyField(null=True, to=settings.AUTH_USER_MODEL, verbose_name='Maintainers'),
        ),
    ]
