# Generated by Django 2.1.2 on 2018-11-14 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0013_auto_20181114_2351'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zentaocase',
            name='tags',
            field=models.ManyToManyField(blank=True, null=True, to='cases.Tag', verbose_name='Tags'),
        ),
    ]
