# Generated by Django 2.1.2 on 2018-11-14 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flows', '0004_auto_20181114_2351'),
    ]

    operations = [
        migrations.AlterField(
            model_name='periodic',
            name='stage',
            field=models.CharField(max_length=25, verbose_name='Stage'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='stage',
            field=models.CharField(max_length=25, verbose_name='Stage'),
        ),
    ]
